import { MAIL_DOMAIN, SITE_NAME } from "./config";

// The address mail is actually received at, which is not yet on SITE_DOMAIN.
// Printing an address SES does not accept would send support mail nowhere.
export const SUPPORT_EMAIL = `support@${MAIL_DOMAIN}`;
export const LEGAL_UPDATED = "September 2026";

export const TERMS = [
  ["Service", `${SITE_NAME} is a service for generating short videos from text and image prompts using third-party AI models, delivered through our website. You must be at least 18 to use it.`],
  ["Plans and credits", `Every account has a plan. The free plan includes a one-off credit allocation; paid plans are billed monthly or annually via our payment processor and include a credit allocation each month, and only paid plans can buy additional credits. Credits are consumed at the price quoted before each generation and are non-transferable. Credits included with a plan EXPIRE when the plan's period renews, except where your plan states that unused credits carry over; credits you buy do not expire. PLAN FEES ARE NOT REFUNDABLE: if you cancel your plan or deactivate your account, your access continues until the end of the billing period you have already paid for, and the account moves to the free plan after that date. Credits you bought can be refunded less costs already incurred — see our Refund Policy.`],
  ["Acceptable use", `You may not use the service to create content that is unlawful, sexual involving minors, non-consensual intimate imagery, deceptive impersonation of real people, harassment, or that infringes others' intellectual property. Prompts and outputs pass automated moderation; rejected generations are refunded. We may suspend accounts that violate this section.`],
  ["AI-generated content", `All videos produced by ${SITE_NAME} are synthetic, generated by AI models from your prompts and inputs. You are responsible for disclosing that content is AI-generated where the law or a platform requires it (for example under the EU AI Act's transparency rules), and for not presenting synthetic depictions of real people or events as genuine.`],
  ["Your content", `You retain rights to the prompts and images you upload and to the videos generated for you, subject to the terms of the underlying model providers. You grant us the limited licence needed to process, store and deliver your content. We do not use your prompts or outputs to train models.`],
  ["Storage", `Generated videos are stored up to your plan's storage quota. If a paid plan lapses, your account reverts to the free plan's quota and videos above it may be deleted after 30 days.`],
  ["Availability", `Generation depends on third-party providers and is offered as-is. Failed generations are refunded automatically. We are not liable for indirect or consequential losses; our total liability is limited to the amount you paid us in the preceding three months.`],
  ["Changes", `We may update these terms; material changes will be announced on the site. Continued use after a change constitutes acceptance.`],
  ["Contact", `Questions: ${SUPPORT_EMAIL}.`],
];

export const PRIVACY = [
  ["What we collect", `Your email address and a hashed password; payment details are handled entirely by our payment processor (Stripe) and never touch our servers; the prompts, reference images and videos you create; and standard server logs.`],
  ["How we use it", `To run the service: authenticating you, processing generations with our AI providers, billing, delivering your videos, and support. Prompts and images are sent to the AI providers strictly to fulfil your request.`],
  ["Sharing", `We share data only with the processors needed to operate: our payment processor, cloud hosting (Amazon Web Services), email delivery, and the AI model providers that generate your videos. We do not sell personal data.`],
  ["Retention", `Account data is kept while your account exists. Videos are kept per the storage terms. You can delete videos at any time, and you can delete your entire account yourself from your account page — that removes your videos from storage and erases your account, history and credits, permanently. You may also deactivate instead, which stops billing and generation but keeps everything until you return. Questions: ${SUPPORT_EMAIL}.`],
  ["Cookies", `We use a single session cookie to keep you signed in. No advertising trackers.`],
  ["Your rights", `You may access, correct or delete your personal data by contacting ${SUPPORT_EMAIL}. Depending on your jurisdiction you may have further rights under applicable data-protection law.`],
  ["Contact", `${SUPPORT_EMAIL}.`],
];

export const REFUNDS = [
  ["Failed generations", `If a generation fails for any reason, the credits are returned to your balance automatically — no request needed.`],
  ["Plan fees are not refunded", `Plan fees are not refundable. What you get instead is the period you paid for: cancelling your plan or deactivating your account keeps your access running to the end of the current billing period, and it is only after that date that the account moves to Free. We do not prorate partial periods. This applies however far into a period you cancel, except where the law requires otherwise, and except where you were charged in error — for that, contact us within 14 days and we will refund it in full.`],
  ["Credits can be refunded, less costs", `Credits you BOUGHT can be refunded to the original payment method. Two costs come off the amount returned, because both have already left our hands: credits you have already spent (the provider was paid to render those videos the moment they were made, so there is nothing to return), and the card processing fee on the original purchase, which our payment processor keeps when a payment is refunded. So a refund returns the value of your unused bought credits, minus that processing fee. Credits included with a plan are not refundable in any amount — they were granted, not purchased, and no money sits behind them. Request a refund at ${SUPPORT_EMAIL}.`],
  ["Credit expiry", `Credits you buy do not expire. Credits included with a plan expire when the plan's period renews, beyond any carry-over your plan states.`],
  ["Quality", `Generated video is probabilistic: an output you dislike is not a failure and isn't refundable, but if a result is clearly broken (corrupt file, wrong length) contact ${SUPPORT_EMAIL} and we'll put it right.`],
];
