#!/usr/bin/env python3
"""Build the tab icon: a black R on a white rounded tile with a hairline edge.

White, not black: the tile has to read on a dark tab strip as well as a
light one, and a white tile with a hairline border does both — a black disc
vanished into a dark tab bar and a bare white R looked borderless.

There is no logo beyond the wordmark, so the icon must be the SAME letter the
wordmark is set in — Geist SemiBold, the weight the header uses — not a
lookalike. A favicon that declares `font-family: sans-serif` renders as a
different R on every platform, so the glyph outline is extracted from the real
font file and embedded as a path.

The font comes from whatever next/font/google actually downloaded for this
build, so the icon cannot drift away from the site's type: if the wordmark's
font ever changes, re-running this picks up the new one.

    python3 scripts/make-favicon.py

Writes web/app/icon.svg, and web/app/favicon.ico alongside it — Next.js
serves favicon.ico in preference to icon.svg, so leaving a stale .ico in place
would quietly override the new icon.

Needs: pip install fonttools brotli cairosvg pillow
"""

import glob
import os
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")

# Matches the header: `font-semibold` is 600.
WEIGHT = 600
# Cap height as a share of the icon's width. Tuned for 16px: much smaller and
# the R is unreadable in a tab; much larger and the circle stops reading as a
# circle.
CAP_RATIO = 0.56
SIZE = 64  # viewBox units; an SVG scales, this is just a convenient grid.
INK = "#0a0a0a"  # the site's --ink in light mode, i.e. the wordmark's own black
GROUND = "#ffffff"
EDGE = "#d4d4d8"  # a hairline so the tile has a shape on a white tab strip too
RADIUS = 14


def geist_regular() -> str:
    """The Geist latin subset this build downloaded, identified by content."""
    for path in sorted(glob.glob(os.path.join(WEB, ".next/static/media/*.woff2"))):
        try:
            font = TTFont(path, fontNumber=0)
        except Exception:
            continue
        family = font["name"].getDebugName(1) or ""
        if family != "Geist":
            continue  # Geist Mono is a different family and the wrong letter
        if "R" not in {chr(c) for c in font.getBestCmap()}:
            continue  # a subset that does not carry the glyph we need
        return path
    raise SystemExit(
        "No Geist latin subset with an 'R' under web/.next/static/media.\n"
        "Run `npm run build` in web/ first so next/font downloads it."
    )


def main() -> None:
    src = geist_regular()
    font = instancer.instantiateVariableFont(TTFont(src, fontNumber=0), {"wght": WEIGHT})
    upem = font["head"].unitsPerEm
    glyph_set = font.getGlyphSet()
    name = font.getBestCmap()[ord("R")]

    pen = SVGPathPen(glyph_set)
    glyph_set[name].draw(pen)
    path = pen.getCommands()

    # The glyph's own bounds, so the R is centred on its ink rather than on its
    # advance width — the two are not the same and the difference is visible at
    # 16 pixels.
    glyf = font["glyf"][name]
    x_min, y_min, x_max, y_max = glyf.xMin, glyf.yMin, glyf.xMax, glyf.yMax

    scale = (SIZE * CAP_RATIO) / (y_max - y_min)
    cx = SIZE / 2 - ((x_min + x_max) / 2) * scale
    # Font units run Y-up, SVG runs Y-down: negate the scale and offset from
    # the glyph's top.
    cy = SIZE / 2 + ((y_min + y_max) / 2) * scale

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}">
  <!-- Generated by scripts/make-favicon.py — do not hand-edit.
       The R is Geist SemiBold, the wordmark's own letterform, embedded as an
       outline so it renders identically everywhere. -->
  <rect x="0.5" y="0.5" width="{SIZE - 1}" height="{SIZE - 1}" rx="{RADIUS}" fill="{GROUND}" stroke="{EDGE}" stroke-width="1"/>
  <path transform="translate({cx:.3f} {cy:.3f}) scale({scale:.6f} {-scale:.6f})" d="{path}" fill="{INK}"/>
</svg>
"""
    out = os.path.join(WEB, "app", "icon.svg")
    with open(out, "w") as fh:
        fh.write(svg)
    print(f"font  : {os.path.relpath(src, ROOT)} @ wght {WEIGHT}")
    print(f"glyph : {name}  bounds {x_min},{y_min} .. {x_max},{y_max}  upem {upem}")
    print(f"wrote : {os.path.relpath(out, ROOT)} ({len(svg)} bytes)")
    write_ico(svg)


def write_ico(svg: str) -> None:
    """The same artwork as a multi-size .ico, or a clear note if we cannot."""
    try:
        import io

        import cairosvg
        from PIL import Image
    except ImportError:
        print("note  : cairosvg/pillow missing — favicon.ico NOT regenerated.")
        print("        pip install cairosvg pillow, then re-run.")
        return

    sizes = [16, 32, 48, 64, 128, 256]
    # Pillow builds every size in an .ico by DOWNSAMPLING the image it is
    # given — `append_images` is not honoured here — so render once at the
    # largest size and let it derive the rest from that.
    base = Image.open(
        io.BytesIO(cairosvg.svg2png(bytestring=svg.encode(), output_width=max(sizes), output_height=max(sizes)))
    ).convert("RGBA")
    out = os.path.join(WEB, "app", "favicon.ico")
    base.save(out, format="ICO", sizes=[(n, n) for n in sizes])
    with Image.open(out) as check:
        got = sorted(check.info.get("sizes", []))
    print(f"wrote : {os.path.relpath(out, ROOT)} ({', '.join(f'{w}x{h}' for w, h in got)})")


if __name__ == "__main__":
    sys.exit(main())
